# 由 EnvGenerator 生成，可以修改参数值，不要直接修改参数属性
# 开发环境
version: '2'

services:
  app:
    image: daocloud.io/krissss/docker-yii2_71:v1.7
    ports:
      - 10080:80
    volumes:
      - .:/app
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- ./docker/supervisor/queue.conf:/etc/supervisor/conf.d/queue.conf
      - C:\Users\<user>\AppData\Roaming\Composer:/tmp
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - D:\docker\yii2advanced\mysql_data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root@128931237
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=yii2advanced@12378243
  redis:
    image: redis:3.2
    ports:
      - 16379:6379
    volumes:
      - D:\docker\yii2advanced\redis_data:/data
    command: >
      --bind 0.0.0.0
      --requirepass yii2advanced@123324
